# Generated by Django 3.1 on 2020-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
